version: '3'

includes:
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  iac:
    taskfile: ./iac/Taskfile.yml
    dir: ./iac

tasks:
  serve:
    desc: Start client HMR and server file-watcher in parallel
    cmds:
      - task -p client:dev server:watch

  deploy:
    desc: Build frontend, then deploy the full stack to fly.io
    deps: [client:build]
    cmds:
      - flyctl deploy --config iac/fly.toml

  default:
    internal: true
    cmds:
      - task --list
